name: Sync to Hugging Face

on:
  push:
    branches:
      - main

jobs:
  push-to-hf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub repo
      uses: actions/checkout@v3

    - name: Configure Git
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"

    - name: Push to Hugging Face
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        git clone https://huggingface.co/spaces/kunalsuri/european-genai-hub hf-space
        rsync -av --exclude='.git' ./ hf-space/
        cd hf-space
        git add .
        git commit -m "Sync from GitHub" || echo "No changes to commit"
        git push https://kunalsuri:$HF_TOKEN@huggingface.co/spaces/kunalsuri/european-genai-hub main
